### ISSUE TITLE
DMON management system

### ISSUE THREAD

**Issue by igabriel85** [dice-project/DICE-Deployment-Service#1]
During the third year we will create a distributed management system for DMON.

It will be able to:

- Scale logstash and elasticsearch instances
- change configuration options

Because of the need to potentially provision additional VMs could we use the Deployment service to 
enact these changes?

We will provide the YAML and Chef recipes. Do you think it is feasible?

**Comment by matejart** [comment]
Cloudify has facility for scaling up/down, but we haven't used it in the DICE deployer yet. But we can certainly use Chef cookbooks we already have (some modificiations will likely be needed, but hopefully not too much) and employ Cloudify directly.

We will look into this.

**Comment by matejart** [comment]
Giuliano's comment in Bordeaux was that the dynamic scaling of the DICE services is not something he sees in the scope of the DICE project.

That said, I think that having a more distributed DMon+ELK would be beneficial already in the DICE project. So if you can provide Chef cookbooks updated to support that, we will extend the TOSCA blueprint for the DMon.
