### ISSUE TITLE
MongoDB Monitoring

### ISSUE THREAD

**Issue by igabriel85** [dice-project/DICE-Deployment-Service#2]
The introduction of MongoDB introduced some new requirements for the installation of the dmon-agent.

- we might require a specific user for monitoring mongodb
it’s not mandatory but it is recommended for security reasons

- We use the python plugin for collectd which loads from dmon-agent home directory the file called mongodb.py  the deployment service only doesn’t have to do anything special as long as the latest version of dmon-agent is used, all new python modules have been upgraded in the _requirements.txt_

- the  new dice.db metrics definition has to be copied from _<AGENT_HOME>/templates/dice.db_ to _/usr/share/collectd/dice.db_

**Comment by tadeboro** [comment]
This is now implemented in DICE TOSCA library.

Relevant commits:
  * https://github.com/dice-project/DICE-Deployment-Cloudify/commit/1cecb2936d4ac72ac12ed8e5485ae6e0b7b30742
  * https://github.com/dice-project/DICE-Deployment-Cloudify/commit/83d7f98faa83d010fc62d718ca441156d827ade3
  * https://github.com/dice-project/DICE-Deployment-Cloudify/commit/42635134db817fb1e9f62b5e231b96f7c14ef135
