### ISSUE TITLE
Cassandra Monitoring

### ISSUE THREAD

**Issue by igabriel85** [dice-project/DICE-Deployment-Service#3]
Cassandra Monitoring introduced some changes to the way the dmon-agent has to be installed:

- requires GenericJMX and Java Plugins from collectd (by default they are installed)
There is a known bug for the java plugin that hardcodes the JDK location in collectd to a specific version. There are two possibilities to fix this:

     - Create a simlink from the actual JDK location to the one needed by collectd (I prefer this quick and dirty hack :) )

     - Compile collectd from the sources
We had to extend collectd metric type definition database to encompass the new metrics
We created dice.db which has to be copied to /usr/share/collectd/

- The hardcoding is in _/usr/lib/collectd/java.so_. The desired location can be listed using:

`strings /usr/lib/collectd/java.so | grep jre`

- the new dice.db metrics definition has to be copied from <AGENT_HOME>/templates/dice.db to /usr/share/collectd/dice.db

**Comment by matejart** [comment]
We have resolved this in Chef cookbooks [v. 0.1.9](https://github.com/dice-project/DICE-Chef-Repository/releases/tag/0.1.9) (at the moment still a develop branch, but soon to be tagged) and thus will be active in the TOSCA library [v. 0.2.5](https://github.com/dice-project/DICE-Deployment-Cloudify/releases/tag/0.2.5).
